### PR TITLE
Rename collection operator middleware

### PR DESCRIPTION
**Pull request by kumaya**
- refactor the name to match gRPC-gateway convention
  - fix minor issue in README.md
  - fix test cases to match new naming convention
  - referencing issue #24

### CODE REVIEW

**Comment by ZachEddy** [comment]
@dmacthedestroyer To clarify: is this what you have in mind?

```sh
# atlas-app-toolkit/middleware
$ tree -A -C middleware
middleware
├── README.md
├── auth
│   ├── interceptor.go
│   ├── interceptor_test.go
│   ├── jwt.go
│   ├── jwt_test.go
│   ├── options.go
│   └── options_test.go
└── collections
    ├── operator.go
    └── operator_test.go
```
In this case, `collections` will be the new package name.
```sh
# atlas-app-toolkit/operators
$ tree -A -C operators
operators
├── collection_operators.pb.go
├── collection_operators.proto
├── fields.go
├── fields_test.go
├── filtering.go
├── filtering_lexer.go
├── filtering_lexer_test.go
├── filtering_parser.go
├── filtering_parser_test.go
├── filtering_test.go
├── gorm
│   ├── collection_operators.go
│   ├── collection_operators_test.go
│   ├── filtering.go
│   └── filtering_test.go
├── pagination.go
├── pagination_test.go
├── sorting.go
└── sorting_test.go
```

**Comment by dmacthedestroyer** [comment]
@ZachEddy Hmm... maybe it should be `collections` at both packages? I kinda sucks having the same name for them, but it also kinda sucks calling one `operators` and the other `collections` when they're the same thing.

The other option is that we don't have a `middleware` package and instead put the middlewares in their respective packages. In this case there'd be a `collections/middleware` package and an `auth/middleware` package. I'm kind of leaning towards that, now.

**Comment by ZachEddy** [comment]
> The other option is that we don't have a middleware package and instead put the middlewares in their respective packages. In this case, there'd be a collections/middleware package and an auth/middleware package. I'm kind of leaning towards that, now.

I'm a fan of this approach. Do you think we can remove the `/middleware` subdirectory altogether? As in, we'll just have `atlas-app-toolkit/auth` and `atla-app-toolkit/collections`? I'm trying to think of the most developer-friendly approach.

**Comment by dmacthedestroyer** [comment]
> Do you think we can remove the /middleware subdirectory altogether?
I'm a fan of this approach :)

In this case, it'd be `collections.UnaryServerInterceptor()` and `auth.UnaryServerInterceptor()` or something like that. Right?

**Comment by ZachEddy** [comment]
Yep! In its current state, authorization middleware is added by calling `auth.DefaultAuthInterceptor()`, so that will need to get changed.

**Comment by kumaya** [comment]
Removing mw and moving operators to collection (renamed op) impose issue of cyclic imports, where mc/operators.go import gw and vice versa gw/fields.go imports op.

**Comment by dmacthedestroyer** [comment]
what a mess! You [nerd sniped](https://xkcd.com/356/) me and I took a stab at this with PR #31. Take a look at it and let me know what you think!

**Comment by dmacthedestroyer** [comment]
closing in favor of #31

**Pull request closed without merging**
